name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: pablomk7/libctrpf:0.8.0

    steps:
      - uses: actions/checkout@v2

      - name: Build Plugin
        run: make

      - name: Upload Plugin
        uses: actions/upload-artifact@v4
        with:
          name: Plugin 3GX File
          path: CTRPluginFramework-BlankTemplate.3gx

      - name: Upload Plugin ELF
        uses: actions/upload-artifact@v4
        with:
          name: Plugin ELF File
          path: CTRPluginFramework-BlankTemplate.elf

      - name: Update git tag
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: richardsimko/update-tag@v1
        with:
          tag_name: git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish git release
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: git
          name: Git
          prerelease: true
          make_latest: false
          files: |
            CTRPluginFramework-BlankTemplate.3gx
            CTRPluginFramework-BlankTemplate.elf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
